[server]
port = 8501
# address = "localhost"  # Commented out for Streamlit Cloud compatibility
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#FF9900"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

# Streamlit Cloud specific settings
[global]
developmentMode = false 